## Pandas Series is a 1D labelled array

## Series and DataFrame

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\RW Zeeshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\RW Zeeshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\RW Zeeshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\RW Zeeshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.6 MB 9.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.6 MB 6.5 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.6 MB 6.6 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.6 MB 7.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 8.3 MB/s  0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [26]:
arr2 = pd.Series(arr1,index=[1,2,3,4,5])

In [27]:
arr2

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [23]:
print(arr2['A'])

1

In [28]:
print(arr2[1:5])

2    2
3    3
4    4
5    5
dtype: int64

## Indexing :
### if labels are of string, then we can't access through numerical indexes
## Slicing:
### In slicing if we try to access elements through string indexes/labels then it'll include the stop/last element as well
### In slicing if we try to access elements through numerical indexes then it won't include the stop/last element like range() or list slicing

In [29]:
lst = [1,2,3,4,5]

In [30]:
for i in range(5):
    print(i)

0
1
2
3
4

In [31]:
df = pd.read_csv('us_average_prices_monthly.csv')

In [33]:
df

,date,year,month,item,unit,category,price,series_id
0,2015-01-01,2015,1,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.211,APU0000FD2101
1,2015-02-01,2015,2,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.221,APU0000FD2101
2,2015-03-01,2015,3,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.176,APU0000FD2101
3,2015-04-01,2015,4,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",2.971,APU0000FD2101
4,2015-05-01,2015,5,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.045,APU0000FD2101
...,...,...,...,...,...,...,...,...
8864,2026-03-01,2026,3,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.560,APU0000FJ4101
8865,2026-04-01,2026,4,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.509,APU0000FJ4101
8866,2026-05-01,2026,5,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.537,APU0000FJ4101
8867,2026-06-01,2026,6,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.587,APU0000FJ4101
8868,2026-07-01,2026,7,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.553,APU0000FJ4101

In [39]:
df.head(8000)

,date,year,month,item,unit,category,price,series_id
0,2015-01-01,2015,1,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.211,APU0000FD2101
1,2015-02-01,2015,2,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.221,APU0000FD2101
2,2015-03-01,2015,3,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.176,APU0000FD2101
3,2015-04-01,2015,4,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",2.971,APU0000FD2101
4,2015-05-01,2015,5,All Ham (Excluding Canned Ham and Luncheon Sli...,lb. (453.6 gm),"Meat, broad category",3.045,APU0000FD2101
...,...,...,...,...,...,...,...,...
7995,2018-07-01,2018,7,"Strawberries, dry pint",12 oz. (340.2 gm),Fruit,2.007,APU0000711415
7996,2018-08-01,2018,8,"Strawberries, dry pint",12 oz. (340.2 gm),Fruit,2.004,APU0000711415
7997,2018-09-01,2018,9,"Strawberries, dry pint",12 oz. (340.2 gm),Fruit,2.147,APU0000711415
7998,2018-10-01,2018,10,"Strawberries, dry pint",12 oz. (340.2 gm),Fruit,2.216,APU0000711415
7999,2018-11-01,2018,11,"Strawberries, dry pint",12 oz. (340.2 gm),Fruit,2.502,APU0000711415

In [37]:
df.tail()

,date,year,month,item,unit,category,price,series_id
8864,2026-03-01,2026,3,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.560,APU0000FJ4101
8865,2026-04-01,2026,4,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.509,APU0000FJ4101
8866,2026-05-01,2026,5,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.537,APU0000FJ4101
8867,2026-06-01,2026,6,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.587,APU0000FJ4101
8868,2026-07-01,2026,7,Yogurt,8 oz. (226.8 gm),Dairy and fats,1.553,APU0000FJ4101

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8869 entries, 0 to 8868
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       8869 non-null   str
 1   year       8869 non-null   int64
 2   month      8869 non-null   int64
 3   item       8869 non-null   str
 4   unit       8869 non-null   str
 5   category   8869 non-null   str
 6   price      8869 non-null   float64
 7   series_id  8869 non-null   str
dtypes: float64(1), int64(2), str(5)
memory usage: 554.4 KB

In [55]:
df1 = pd.DataFrame(arr2)

In [56]:
df1

   0
1  1
2  2
3  3
4  4
5  5